# perturb.py
import math
import pprint
import string
import random
import itertools
import os
from collections import deque
from typing import Any, TypeVar

"""
all of the tokenize functions are generated by chat I did not feel like reimplementing that myself
"""

# Leet speak mapping
LEET_MAP = {
    '4': 'a', '@': 'a', '8': 'b', '(': 'c', '{': 'c', 
    '[': 'c', '<': 'c', '3': 'e', '6': 'g', '9': 'g', 
    '1': 'i', '!': 'i', '|': 'i', '7': 'l', '0': 'o',
    '$': 's', '5': 's', '+': 't', '%': 'x', '2': 'z'
}

# Global trie for word lookups
_word_trie: dict[str, dict[str, Any]] | None = None

T = TypeVar("T")

def _load_word_lists():
    """Load word lists into a trie structure for efficient lookup."""
    global _word_trie
    if _word_trie is not None:
        return _word_trie
    
    _word_trie = {}
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    wordlist_paths = [
        os.path.join(script_dir, "data/original-wordlists/english_wikipedia.txt"),
        os.path.join(script_dir, "data/original-wordlists/us_tv_and_film.txt"),
        os.path.join(script_dir, "data/original-wordlists/surnames.txt"),
        os.path.join(script_dir, "data/original-wordlists/male_names.txt"),
        os.path.join(script_dir, "data/original-wordlists/female_names.txt"),
    ]
    
    for path in wordlist_paths:
        if not os.path.exists(path):
            continue
        with open(path, 'r') as f:
            for line in f:
                # Get rid of non-alphabetic characters and convert to lowercase
                word = ''.join(c for c in line.strip() if c.isalpha()).lower()
                if not word:
                    continue
                
                # Split into chunks of 2 characters (1-char tokens at the end)
                chunks = [word[i:i+2] for i in range(0, len(word), 2)]
                curr = _word_trie
                for i, chunk in enumerate(chunks):
                    if chunk not in curr:
                        curr[chunk] = {"_is_word": False, "children": {}}
                    if i == len(chunks) - 1:
                        curr[chunk]["_is_word"] = True
                    curr = curr[chunk]["children"]
    
    return _word_trie

def _generate_unleet(password: str) -> list[str]:
    """Generate all possible un-leeted versions of a password."""
    results = []
    
    def backtrack(index, current):
        if index == len(password):
            results.append(current)
            return
        
        c = password[index]
        # Check if this character has leet substitutions
        found_leet = False
        for leet_char, original_char in LEET_MAP.items():
            if leet_char == c:
                found_leet = True
                backtrack(index + 1, current + original_char)
        
        # Also add the character as-is
        backtrack(index + 1, current + c)
    
    backtrack(0, "")
    return results

def _find_word(password: str, start_idx: int) -> int:
    """
    Find the longest word starting at start_idx in the password.
    Returns the length of the word found, or 0 if no word.
    Tries to match 2-character tokens first, then 1-character as fallback.
    """
    global _word_trie
    if _word_trie is None:
        _load_word_lists()
    if _word_trie is None:
        return 0
    
    trie = _word_trie
    idx = start_idx
    last_valid_depth = 0
    last_valid_chars_consumed = 0  # Track the chars_consumed from last valid update
    current_depth = 0
    pw_len = len(password)
    
    while idx < pw_len:
        chars_consumed = 0
        
        # Try 2-character token first
        if idx + 1 < pw_len:
            two_char = password[idx:idx+2]
            if two_char in trie:
                current_depth += 1
                if trie[two_char]["_is_word"]:
                    last_valid_depth = current_depth
                    last_valid_chars_consumed = 2
                # Move to children if they exist
                if trie[two_char]["children"]:
                    trie = trie[two_char]["children"]
                    idx += 2
                    chars_consumed = 2
                else:
                    break
            else:
                # Try 1-character fallback
                one_char = password[idx]
                if one_char in trie:
                    current_depth += 1
                    if trie[one_char]["_is_word"]:
                        last_valid_depth = current_depth
                        last_valid_chars_consumed = 1
                    # Move to children if they exist
                    if trie[one_char]["children"]:
                        trie = trie[one_char]["children"]
                        idx += 1
                        chars_consumed = 1
                    else:
                        break
                else:
                    break
        else:
            # Only 1 char left in password
            one_char = password[idx]
            if one_char in trie:
                current_depth += 1
                if trie[one_char]["_is_word"]:
                    last_valid_depth = current_depth
                    last_valid_chars_consumed = 1
                # Move to children if they exist
                if trie[one_char]["children"]:
                    trie = trie[one_char]["children"]
                    idx += 1
                    chars_consumed = 1
                else:
                    break
            else:
                break
        
        if chars_consumed == 0:
            break
    
    # Return length in original character units
    if last_valid_depth > 0:
        if last_valid_chars_consumed == 2:
            return last_valid_depth * 2
        else:
            return last_valid_depth * 2 - 1
    else:
        return 0

def tokenize(password: str) -> tuple[list[str], list[str]]:
    """
    Tokenizes the password into tokens and their types.
    Returns: (token_list, token_type_list) where token_type is 'w' (word), 'n' (number), 's' (special), or 'o' (other)
    """
    _load_word_lists()
    
    pw_length = len(password)
    tokens = []
    token_types = []
    
    # Create lowercase version and generate all un-leeted versions
    lower_password = password.lower()
    unleet_versions = _generate_unleet(lower_password)
    
    i = 0
    while i < pw_length and len(tokens) < 20:
        # Start position of this token
        token_start = i
        tokens.append(token_start)
        
        # Try to find a word
        max_word_len = 0
        for unleet_version in unleet_versions:
            word_len = _find_word(unleet_version, i)
            if word_len > max_word_len:
                max_word_len = word_len
        
        # Validate 1-2 character words to avoid false positives
        if max_word_len == 1:
            if not ((password[i] >= 'a' and password[i] <= 'z') or (password[i] >= 'A' and password[i] <= 'Z')):
                max_word_len = 0
        if max_word_len == 2:
            if i + 1 < pw_length and not ((password[i + 1] >= 'a' and password[i + 1] <= 'z') or (password[i + 1] >= 'A' and password[i + 1] <= 'Z')):
                max_word_len = 0
        
        if max_word_len > 0:
            token_types.append('w')
            i += max_word_len
        # Check if we have a number
        elif password[i] >= '0' and password[i] <= '9':
            token_types.append('n')
            j = i + 1
            while j < pw_length and password[j] >= '0' and password[j] <= '9':
                j += 1
            i = j
        # Check if we have a special character
        elif ((password[i] >= '!' and password[i] <= '/') or 
              (password[i] >= ':' and password[i] <= '@') or 
              (password[i] >= '[' and password[i] <= '`') or 
              (password[i] >= '{' and password[i] <= '~')):
            token_types.append('s')
            i += 1
        else:
            token_types.append('o')
            i += 1
    
    # Build actual token strings from starting indices
    token_strings = []
    for idx, token_idx in enumerate(tokens):
        if idx < len(tokens) - 1:
            next_token_start = tokens[idx + 1]
        else:
            next_token_start = pw_length
        token_strings.append(password[token_idx:next_token_start])
    
    return token_strings, token_types

def exponential_mech(output_space: list[T], utility_space: list[int], eps: float, sensitivity: float = 1.0) -> T:
    weights = []
    total_weight = 0
    for i in range(len(output_space)):
        weight = math.exp((eps * utility_space[i])/(2 * sensitivity))
        weights.append(weight)
        total_weight += weight

    probabilities = [x / total_weight for x in weights]

    # choose random number 0-1
    rand = random.uniform(0,1)
    selection = output_space[-1]
    cumsum = 0
    # get cumulative sum to see which category our random number falls into
    for i in range(len(probabilities)):
        prob = probabilities[i]
        cumsum += prob
        if rand < cumsum:
            selection = output_space[i]
            break

    return selection

def get_swap_distance(original: list[str], permutation: list[str]) -> int:
    # leetcode type problem lol
    original_map = {element: index for index, element in enumerate(original)}

    permutation_indices = [original_map[element] for element in permutation]

    inversions = 0
    n = len(permutation_indices)
    
    # Count how many times a larger index appears before a smaller index
    for i in range(n):
        for j in range(i + 1, n):
            if permutation_indices[i] > permutation_indices[j]:
                inversions += 1
                
    return -1 * inversions

def semantically_perturb(tokens: list[str], token_types: list[str], eps: float):
    token_permutations = [list(p) for p in itertools.permutations(tokens)]
    token_type_permutations = [list(p) for p in itertools.permutations(token_types)]

    utility_space = [get_swap_distance(tokens, token_permutations[i]) for i in range(len(token_permutations))]

    selected_permutation = exponential_mech(token_permutations, utility_space, eps)

    permutation_index = token_permutations.index(selected_permutation)

    selected_token_type_permutation = token_type_permutations[permutation_index]

    return selected_permutation, selected_token_type_permutation

def perturb_word(word: str, eps: float, nearest_neighbors: int = 10) -> str:
    # Use the global trie that was built from the wordlists.
    # The trie stores 2-character tokens (and sometimes 1-character tail tokens)
    # so we can navigate words in token-sized hops.
    global _word_trie

    # If trie data is unavailable, we cannot compute neighbors.
    # In that case, leave the input unchanged.
    if _word_trie is None:
        return word
    trie = _word_trie

    # A non-positive neighbor request means "do not perturb".
    # Returning the original token keeps behavior deterministic and safe.
    if nearest_neighbors <= 0:
        return word

    # The trie is lowercase, so normalize before lookup.
    # We still preserve original casing at the very end.
    normalized_word = word.lower()

    # Split into the same tokenization scheme used when building the trie.
    # Example: "password" -> ["pa", "ss", "wo", "rd"]
    chunks = [normalized_word[i:i+2] for i in range(0, len(normalized_word), 2)]

    # Walk the trie path for the exact word. If any chunk is missing,
    # this word does not exist in the dictionary/trie and we keep it as-is.
    current_children = trie
    start_path = []
    for chunk in chunks:
        if chunk not in current_children:
            return word
        start_path.append(chunk)
        current_children = current_children[chunk]["children"]

    # Re-resolve the final node and ensure the path is a complete word,
    # not just a prefix used by other words.
    # If it is only a prefix, perturbation is skipped.
    node = trie[start_path[0]]
    for chunk in start_path[1:]:
        node = node["children"][chunk]
    if not node["_is_word"]:
        return word

    # Cache resolved trie nodes by path tuple to avoid repeatedly traversing
    # from the root during BFS expansion.
    node_cache = {}

    def get_node(path: tuple[str, ...]):
        # Fast path: already resolved this tuple-path.
        if path in node_cache:
            return node_cache[path]

        # Empty tuple represents a synthetic root that has all top-level
        # trie tokens as children but is not itself a valid word.
        if len(path) == 0:
            root = {"_is_word": False, "children": trie}
            node_cache[path] = root
            return root

        # Resolve a non-empty path from trie root to the target node.
        n = trie[path[0]]
        for token in path[1:]:
            n = n["children"][token]
        node_cache[path] = n
        return n

    # Breadth-first search over an implicit undirected graph of trie paths:
    # - Up edge: drop one token (go to parent)
    # - Down edges: append one child token
    # BFS guarantees first time we discover a word, it is at minimum traversal
    # distance in number of trie edges from the original word.
    start = tuple(start_path)
    queue = deque([(start, 0)])
    visited = {start}

    # seen_words prevents duplicate string outputs if multiple path encounters
    # could map to the same candidate representation.
    seen_words = set()

    # neighbors and traversal_distances stay index-aligned.
    # traversal_distances stores utility as negative distance:
    # 0 for the same word, -1 one edge away, -2 two edges away, etc.
    neighbors = []
    traversal_distances = []

    # Stop when queue is exhausted or we gathered requested neighbor count.
    while queue and len(neighbors) < nearest_neighbors:
        path, dist = queue.popleft()
        cur = get_node(path)

        # If this path is a complete word, add it as a candidate.
        # Only keep neighbors with length > 2 to avoid tiny/low-signal words.
        if cur["_is_word"]:
            candidate = "".join(path)
            if candidate not in seen_words:
                seen_words.add(candidate)
                neighbors.append(candidate)
                traversal_distances.append(-dist)

        # Explore one step upward (parent path).
        if len(path) > 0:
            parent = path[:-1]
            if parent not in visited:
                visited.add(parent)
                queue.append((parent, dist + 1))

        # Explore one step downward to each child path.
        # Sorting keeps traversal order deterministic across runs/Python versions.
        for child_token in sorted(cur["children"].keys()):
            child = path + (child_token,)
            if child not in visited:
                visited.add(child)
                queue.append((child, dist + 1))

    # If no neighbors were found (unexpected but possible on malformed trie),
    # keep the original token.
    if not neighbors:
        return word
    
    # Debug print currently left in place to show candidate space and utilities.
    # Example format: ['password', 'pass', ...] [0, -1, ...]
    # print(neighbors, traversal_distances)

    # Sample a replacement with the exponential mechanism.
    # Higher utility (closer to 0 here) gets higher probability.
    selection = exponential_mech(neighbors, traversal_distances, eps)

    # Preserve original capitalization pattern for readability:
    # - ALLCAPS stays ALLCAPS
    # - Titlecase stays Titlecase
    # - everything else remains lowercase candidate from trie
    if word.isupper():
        return selection.upper()
    if len(word) > 0 and word[0].isupper() and word[1:].islower():
        return selection.capitalize()
    return selection

def perturb_number(number: str, eps: float) -> str:
    if (not str.isdigit(number)):
        return number
    
    num_len = len(number)
    max_num = int('9' * num_len)

    output_space = [str(x) for x in range(max_num + 1)]
    utility_space = [-1 * abs(int(number) - int(x)) for x in output_space]

    selection = exponential_mech(output_space, utility_space, eps)

    return selection

def perturb_special(special: str, eps: float) -> str:
    special_chars = [x for x in string.punctuation]
    ret = ""
    for char in special:
        if char not in special_chars:
            special_chars.append(char)

        utility_space = [-1 * abs(ord(char) - ord(x)) for x in special_chars]

        selection = exponential_mech(special_chars, utility_space, eps)
        ret += selection

    return ret

def perturb(password: str, eps: float = 1.0) -> str:
    # print(f"Original Password: {password}")
    tokens, token_types = tokenize(password)
    # print(f"Tokenization: {tokens}")

    semantic_budget = eps / 2
    diction_budget = eps / 2

    tokens, token_types = semantically_perturb(tokens, token_types, semantic_budget)

    budget_per_token = diction_budget / len(tokens)
    for i in range(len(tokens)):
        token = tokens[i]
        token_type = token_types[i]

        if token_type == "w":
            tokens[i] = perturb_word(token, budget_per_token)
        elif token_type == "n":
            tokens[i] = perturb_number(token, budget_per_token)
        elif token_type == "s":
            tokens[i] = perturb_special(token, budget_per_token)
        
    return ''.join(tokens)

def main():
    eps_vals = [0.01, 0.1, 0.25, 0.5, 1.0, 2.0, 5.0, 12.0, 20.0, 50.0, 100.0, 250.0, 1000.0, 5000.0, 10000.0, 25000.0, 50000.0, 100000.0]
    passwords = [
        "Apple432Bottom#",
        "Password123!",
        "LemonJumpSlide1#",
        "MaxPassword",
        "iamaword2",
        "Welcome1",
        "RedTeamSucks3",
    ]

    irsec_passwords = [
        "Change.me123!",
        "things",
        "starburst",
        "PleaseDont5489CH32",
        "Super123!?",
        "VikingWorksAgain!",
        "Shadow#Leaf16@Node89",
        "RedTeamIsUgly!!",
        "White#Comet192@Map28",
        "WhyAreWeStillHere2015?",
        "foobarbaz5",
        "weloveyouredteam",
        "RickerBalls2",
        "Idkwhatimdoinghelp1",
        "ThankYouWhiteTeam"
    ]
    
    # perturbed = {}
    for eps in eps_vals:
        num_different = 0
        # perturbed_passwords = []
        for i in range(100):
            for password in irsec_passwords:
                new_pass = perturb(password, eps)
                if password.lower() != new_pass.lower():
                    num_different += 1
                    # print(f"Epsilon: {eps}, Original: {password}, Perturbed: {new_pass}")
            for password in passwords:
                new_pass = perturb(password, eps)
                if password.lower() != new_pass.lower():
                    num_different += 1
                    # print(f"Epsilon: {eps}, Original: {password}, Perturbed: {new_pass}")
        print(f"Epsilon: {eps}, Different Passwords: {num_different} / {(len(passwords) + len(irsec_passwords)) * 100}")
        # perturbed_passwords.append((password, perturb(password, eps)))
        # perturbed[eps] = perturbed_passwords
    
    # pprint.pprint(perturbed, indent=4)

if (__name__ == '__main__'):
    main()